modLoader = "javafml"
loaderVersion = "[2,)"
license = "LGPLv3"
issueTrackerURL = "https://github.com/JSDforJ/VillagerOverride/issues/new"
clientSideOnly = true

[[mods]]
modId = "villageroverride"
version = "${version}"
displayName = "Villager Override"
authors = "JSDfJ"
description = '''
Allows you to override the biome skins of villagers. For example make every villager looks like a jungle villager.
'''
logoFile = "META-INF/assets/villageroverride/icon.png"
updateJSONURL = "https://raw.githubusercontent.com/JSDforJ/VillagerOverride/refs/heads/master/neoforge-update.json"

[[dependencies.villageroverride]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.villageroverride]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.villageroverride]]
modId = "yet_another_config_lib_v3"
mandatory = true
versionRange = "[3.8.2+1.21.11,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "villageroverride.mixins.json"
